package analyzer

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/opd-ai/go-stats-generator/internal/metrics"
)

// TestCoverageAnalyzer correlates code metrics with test coverage
type TestCoverageAnalyzer struct {
	coverageData map[string]map[int]int // file -> line -> hit count
}

// NewTestCoverageAnalyzer creates a test coverage analyzer for correlating code metrics with
// test coverage data. This analyzer loads Go coverage profiles, maps coverage to specific
// functions and lines, and identifies undertested complex code. Essential for test gap analysis
// and prioritizing test writing efforts based on complexity and coverage correlation.
func NewTestCoverageAnalyzer() *TestCoverageAnalyzer {
	return &TestCoverageAnalyzer{
		coverageData: make(map[string]map[int]int),
	}
}

// LoadCoverageProfile parses a Go coverage profile file (generated by `go test -coverprofile`)
// and loads line-level hit count data into the analyzer. Coverage data enables correlation analysis
// between code complexity and test coverage, helping identify high-risk untested code. Returns error
// if the profile file cannot be read or parsed.
func (a *TestCoverageAnalyzer) LoadCoverageProfile(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open coverage: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "mode:") {
			continue
		}
		if err := a.parseCoverageLine(line); err != nil {
			return err
		}
	}
	return scanner.Err()
}

// parseCoverageLine parses a single line from Go coverage profile and records coverage data
func (a *TestCoverageAnalyzer) parseCoverageLine(line string) error {
	file, startLine, endLine, count, err := extractCoverageFields(line)
	if err != nil {
		return err
	}
	if file == "" {
		return nil
	}

	a.recordCoverage(file, startLine, endLine, count)
	return nil
}

// extractCoverageFields extracts file path, line range, and hit count from coverage line
func extractCoverageFields(line string) (file string, startLine, endLine, count int, err error) {
	parts := strings.Fields(line)
	if len(parts) < 3 {
		return "", 0, 0, 0, nil
	}

	file, startLine, endLine, err = parseFileAndRange(parts[0])
	if err != nil || file == "" {
		return "", 0, 0, 0, err
	}

	count, err = strconv.Atoi(parts[2])
	return file, startLine, endLine, count, err
}

// parseFileAndRange extracts file path and line range from coverage file specification
func parseFileAndRange(fileSpec string) (file string, startLine, endLine int, err error) {
	fileAndRange := strings.Split(fileSpec, ":")
	if len(fileAndRange) != 2 {
		return "", 0, 0, nil
	}

	file = fileAndRange[0]
	ranges := strings.Split(fileAndRange[1], ",")
	if len(ranges) != 2 {
		return "", 0, 0, nil
	}

	startLine, err = parseLineNum(ranges[0])
	if err != nil {
		return "", 0, 0, err
	}
	endLine, err = parseLineNum(ranges[1])
	if err != nil {
		return "", 0, 0, err
	}

	return file, startLine, endLine, nil
}

// recordCoverage stores coverage hit counts for specified file and line range
func (a *TestCoverageAnalyzer) recordCoverage(file string, startLine, endLine, count int) {
	if a.coverageData[file] == nil {
		a.coverageData[file] = make(map[int]int)
	}

	for i := startLine; i <= endLine; i++ {
		a.coverageData[file][i] += count
	}
}

// parseLineNum extracts the line number from a coverage profile line specification.
func parseLineNum(s string) (int, error) {
	parts := strings.Split(s, ".")
	return strconv.Atoi(parts[0])
}

// AnalyzeCorrelation generates comprehensive coverage metrics by correlating test coverage data
// with code complexity, identifying high-risk functions (complex but untested), calculating coverage
// rates for both functions and complexity-weighted lines, and detecting coverage gaps. This analysis
// prioritizes testing efforts on the most critical code paths. Returns detailed coverage correlation metrics.
func (a *TestCoverageAnalyzer) AnalyzeCorrelation(functions []metrics.FunctionMetrics) metrics.TestCoverageMetrics {
	result := metrics.TestCoverageMetrics{
		HighRiskFunctions: []metrics.HighRiskFunction{},
		CoverageGaps:      []metrics.CoverageGap{},
	}

	totalFunctions, coveredFunctions, totalComplexity, coveredComplexity := a.aggregateFunctionMetrics(functions, &result)

	result.FunctionCoverageRate = a.calculateCoverageRate(float64(coveredFunctions), float64(totalFunctions))
	result.ComplexityCoverageRate = a.calculateCoverageRate(coveredComplexity, totalComplexity)

	sort.Slice(result.HighRiskFunctions, func(i, j int) bool {
		return result.HighRiskFunctions[i].RiskScore > result.HighRiskFunctions[j].RiskScore
	})

	return result
}

// aggregateFunctionMetrics collects coverage statistics across all functions.
func (a *TestCoverageAnalyzer) aggregateFunctionMetrics(functions []metrics.FunctionMetrics, result *metrics.TestCoverageMetrics) (totalFunctions, coveredFunctions int, totalComplexity, coveredComplexity float64) {
	for _, fn := range functions {
		coverage := a.calculateFunctionCoverage(fn)
		totalFunctions++
		totalComplexity += fn.Complexity.Overall

		if coverage > 0 {
			coveredFunctions++
			coveredComplexity += fn.Complexity.Overall
		}

		a.collectHighRiskFunctions(fn, coverage, result)
		a.collectCoverageGaps(fn, coverage, result)
	}
	return totalFunctions, coveredFunctions, totalComplexity, coveredComplexity
}

// collectHighRiskFunctions adds high-risk functions to the result based on complexity and coverage.
func (a *TestCoverageAnalyzer) collectHighRiskFunctions(fn metrics.FunctionMetrics, coverage float64, result *metrics.TestCoverageMetrics) {
	if a.isHighRisk(fn, coverage) {
		result.HighRiskFunctions = append(result.HighRiskFunctions, metrics.HighRiskFunction{
			Name:       fn.Name,
			File:       fn.File,
			Line:       fn.Line,
			Complexity: fn.Complexity.Cyclomatic,
			Coverage:   coverage,
			RiskScore:  a.calculateRiskScore(fn, coverage),
		})
	}
}

// collectCoverageGaps identifies exported functions with insufficient test coverage.
func (a *TestCoverageAnalyzer) collectCoverageGaps(fn metrics.FunctionMetrics, coverage float64, result *metrics.TestCoverageMetrics) {
	if a.isCoverageGap(fn, coverage) {
		result.CoverageGaps = append(result.CoverageGaps, metrics.CoverageGap{
			Name:        fn.Name,
			File:        fn.File,
			Line:        fn.Line,
			Complexity:  fn.Complexity.Cyclomatic,
			Coverage:    coverage,
			GapSeverity: a.gapSeverity(fn, coverage),
		})
	}
}

// calculateCoverageRate computes coverage percentage handling zero-division safely.
func (a *TestCoverageAnalyzer) calculateCoverageRate(covered, total float64) float64 {
	if total > 0 {
		return covered / total
	}
	return 0.0
}

// calculateFunctionCoverage computes line coverage percentage for a specific function.
func (a *TestCoverageAnalyzer) calculateFunctionCoverage(fn metrics.FunctionMetrics) float64 {
	file := fn.File
	startLine := fn.Line
	endLine := fn.Line + fn.Lines.Total

	if a.coverageData[file] == nil {
		return 0.0
	}

	var covered, total int
	for line := startLine; line <= endLine; line++ {
		total++
		if a.coverageData[file][line] > 0 {
			covered++
		}
	}

	if total == 0 {
		return 0.0
	}
	return float64(covered) / float64(total)
}

// isHighRisk determines if a function poses risk based on complexity and coverage thresholds.
func (a *TestCoverageAnalyzer) isHighRisk(fn metrics.FunctionMetrics, coverage float64) bool {
	return (fn.Complexity.Cyclomatic > 5 && coverage < 0.5) ||
		(fn.Complexity.Cyclomatic > 10 && coverage < 0.8)
}

// isCoverageGap returns true for exported functions with below-threshold coverage.
func (a *TestCoverageAnalyzer) isCoverageGap(fn metrics.FunctionMetrics, coverage float64) bool {
	return coverage < 0.7 && fn.IsExported
}

// calculateRiskScore computes a risk metric combining complexity, coverage, and size factors.
func (a *TestCoverageAnalyzer) calculateRiskScore(fn metrics.FunctionMetrics, coverage float64) float64 {
	score := float64(fn.Complexity.Cyclomatic) * (1.0 - coverage)
	if fn.Lines.Total > 50 {
		score *= 1.5
	}
	return score
}

// gapSeverity categorizes coverage gaps as critical, high, medium, or low based on coverage and complexity.
func (a *TestCoverageAnalyzer) gapSeverity(fn metrics.FunctionMetrics, coverage float64) string {
	if coverage < 0.3 && fn.Complexity.Cyclomatic > 5 {
		return "critical"
	}
	if coverage < 0.5 || fn.Complexity.Cyclomatic > 8 {
		return "high"
	}
	if coverage < 0.7 {
		return "medium"
	}
	return "low"
}

// AnalyzeTestQuality assesses test suite quality by analyzing test file structure, assertion density,
// test case organization, and testing patterns. It walks the repository, parses test files, counts
// assertions, identifies test helpers, and calculates quality metrics like assertions per test and
// test file coverage. Essential for evaluating test effectiveness and identifying weak test suites.
func AnalyzeTestQuality(repoPath string) (metrics.TestQualityMetrics, error) {
	result := metrics.TestQualityMetrics{
		TestFiles: []metrics.TestFileInfo{},
	}

	err := filepath.Walk(repoPath, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}

		if !strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoPath, path)
		testInfo := analyzeTestFile(path, relPath)
		result.TestFiles = append(result.TestFiles, testInfo)
		result.TotalTests += testInfo.TestCount

		return nil
	})
	if err != nil {
		return result, err
	}

	if len(result.TestFiles) > 0 {
		var totalAssertion float64
		for _, tf := range result.TestFiles {
			totalAssertion += tf.AssertionRatio
		}
		result.AvgAssertionsPerTest = totalAssertion / float64(len(result.TestFiles))
	}

	return result, nil
}

// analyzeTestFile examines a test file to extract test quality metrics including test count,
// table-driven test detection, assertion patterns, and helper function usage. This analysis
// provides insights into test design patterns and quality indicators within the test suite.
func analyzeTestFile(path, relPath string) metrics.TestFileInfo {
	info := metrics.TestFileInfo{
		File: relPath,
	}

	content, err := os.ReadFile(path)
	if err != nil {
		return info
	}

	lines := strings.Split(string(content), "\n")
	countTestMetrics(lines, &info)
	calculateAssertionRatio(&info)

	return info
}

// countTestMetrics scans test file lines to count tests, subtests, and assertions.
func countTestMetrics(lines []string, info *metrics.TestFileInfo) {
	for _, line := range lines {
		if strings.Contains(line, "func Test") {
			info.TestCount++
		}
		if strings.Contains(line, "t.Run(") {
			info.SubtestCount++
		}
		if containsAssertion(line) {
			info.AssertionCount++
		}
	}
}

// calculateAssertionRatio computes the average number of assertions per test.
func calculateAssertionRatio(info *metrics.TestFileInfo) {
	if info.TestCount > 0 {
		info.AssertionRatio = float64(info.AssertionCount) / float64(info.TestCount)
	}
}

// containsAssertion checks if a line contains common testing assertion patterns.
func containsAssertion(line string) bool {
	assertions := []string{
		"assert.", "require.", "t.Error", "t.Fatal",
		"!= nil", "== nil", "if err",
	}
	for _, a := range assertions {
		if strings.Contains(line, a) {
			return true
		}
	}
	return false
}
