# Example configuration file for go-stats-generator
# Place this file in your home directory or project root

analysis:
  include_functions: true
  include_structs: true
  include_interfaces: true
  include_patterns: false  # Pattern detection planned for future release
  include_complexity: true
  include_documentation: true
  include_generics: true
  max_function_length: 30
  max_cyclomatic_complexity: 10
  max_struct_fields: 20
  min_documentation_coverage: 0.8

output:
  format: console  # console, json, html
  use_colors: true
  show_progress: true
  include_examples: false
  include_overview: true
  include_details: true
  sort_by: "complexity"
  limit: 100

performance:
  worker_count: 8  # 0 = number of CPU cores
  timeout: 10m
  enable_cache: true
  max_memory_mb: 1024

filters:
  skip_vendor: true
  skip_test_files: false
  skip_generated: true
  include_patterns:
    - "**/*.go"
  exclude_patterns:
    - "vendor/**"
    - "*.pb.go"
    - "testdata/**"

storage:
  type: "sqlite"  # sqlite, json, memory
  path: "metrics.db"
  compression: true
  max_snapshots: 100
  max_age: "90d"
