package scanner

import (
	"path/filepath"
	"strings"
)

// shouldIncludeFile determines if a file should be included in analysis
func (d *Discoverer) shouldIncludeFile(fileInfo FileInfo) bool {
	if !d.passesFileConstraints(fileInfo) {
		return false
	}

	if !d.matchesIncludePatterns(fileInfo) {
		return false
	}

	if d.matchesExcludePatterns(fileInfo) {
		return false
	}

	if !d.passesPackageFilter(fileInfo) {
		return false
	}

	return true
}

// passesFileConstraints checks basic file constraints
func (d *Discoverer) passesFileConstraints(fileInfo FileInfo) bool {
	if d.config.MaxFileSizeKB > 0 && fileInfo.Size > int64(d.config.MaxFileSizeKB*1024) {
		return false
	}

	if d.config.SkipTestFiles && fileInfo.IsTestFile {
		return false
	}

	if d.config.SkipGenerated && fileInfo.IsGenerated {
		return false
	}

	return true
}

// matchesIncludePatterns checks if file matches any include patterns
func (d *Discoverer) matchesIncludePatterns(fileInfo FileInfo) bool {
	if len(d.config.IncludePatterns) == 0 {
		return true
	}

	for _, pattern := range d.config.IncludePatterns {
		if d.patternMatches(pattern, fileInfo.RelPath) {
			return true
		}
	}

	return false
}

// matchesExcludePatterns checks if file matches any exclude patterns
func (d *Discoverer) matchesExcludePatterns(fileInfo FileInfo) bool {
	for _, pattern := range d.config.ExcludePatterns {
		if matched, _ := filepath.Match(pattern, fileInfo.RelPath); matched {
			return true
		}
	}
	return false
}

// passesPackageFilter checks package inclusion/exclusion rules
func (d *Discoverer) passesPackageFilter(fileInfo FileInfo) bool {
	if len(d.config.IncludePackages) > 0 {
		return d.isPackageIncluded(fileInfo.Package)
	}
	return !d.isPackageExcluded(fileInfo.Package)
}

// isPackageIncluded checks if package is in the include list
func (d *Discoverer) isPackageIncluded(pkg string) bool {
	for _, includePkg := range d.config.IncludePackages {
		if pkg == includePkg {
			return true
		}
	}
	return false
}

// isPackageExcluded checks if package is in the exclude list
func (d *Discoverer) isPackageExcluded(pkg string) bool {
	for _, excludePkg := range d.config.ExcludePackages {
		if pkg == excludePkg {
			return true
		}
	}
	return false
}

// patternMatches checks if a file path matches a given pattern
func (d *Discoverer) patternMatches(pattern, relPath string) bool {
	if strings.Contains(pattern, "**") {
		return strings.HasSuffix(relPath, ".go")
	}

	matched, _ := filepath.Match(pattern, relPath)
	return matched
}

// isGeneratedFile checks if a file appears to be generated
func isGeneratedFile(content string) bool {
	lines := strings.Split(content, "\n")
	checkLines := len(lines)
	if checkLines > 10 {
		checkLines = 10
	}

	for i := 0; i < checkLines; i++ {
		line := strings.ToLower(strings.TrimSpace(lines[i]))

		if strings.Contains(line, "code generated") ||
			strings.Contains(line, "do not edit") ||
			strings.Contains(line, "autogenerated") ||
			strings.Contains(line, "auto-generated") ||
			strings.Contains(line, "generated automatically") ||
			strings.Contains(line, "this file was generated") {
			return true
		}
	}

	return false
}

// containsPathSegment checks if a path contains a specific segment
func containsPathSegment(path, segment string) bool {
	normalizedPath := strings.ReplaceAll(path, "\\", "/")
	segments := strings.Split(normalizedPath, "/")
	for _, s := range segments {
		if s == segment {
			return true
		}
	}
	return false
}
